default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2

production:
  <<: *default
  database: makersbnb_production

development:
  <<: *default
  database: makersbnb_development

test:
  <<: *default
  database: makersbnb_testing